apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      # nodeSelector:
      # cloud.google.com/compute-class: Performance
      # kubernetes.io/arch: arm64
      containers:
        - name: my-app
          image: fallenreaper/csc820-mod10:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: my-app-volume
              mountPath: /app/db
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_PATH
              value: "/app/db"
      volumes:
        - name: my-app-volume
          persistentVolumeClaim:
            claimName: my-app-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: standard-rwx
