---
- hosts: server
  become: true
  vars:
    node_major: 24
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
        state: present
        update_cache: yes

    - name: Install PostgreSQL and Python dependencies
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2 # Required for Ansible postgresql modules
          - acl # Required to allow Ansible to become the postgres user
        state: present

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database
      postgresql_db:
        name: my_database
        state: present
      become_user: postgres

    - name: Create database user
      postgresql_user:
        db: my_database
        name: app_user
        password: securepassword123
        state: present
      become_user: postgres

    - name: Grant privileges to user
      community.postgresql.postgresql_privs:
        db: my_database
        role: app_user
        objs: ALL_IN_SCHEMA
        privs: ALL
        state: present
      become: yes
      become_user: postgres

    - name: Find all items except the specific folder
      find:
        paths: ../
        file_type: any
        excludes: "node_modules"
      delegate_to: localhost
      register: items_to_copy
      become: no

    - name: Copy filtered items
      copy:
        src: "{{ item.path }}"
        dest: /home/ubuntu/my-node-app/
      loop: "{{ items_to_copy.files }}"
      become: yes

    - name: Delete node_modules folder on the server if it exists
      file:
        path: /home/ubuntu/my-node-app/node_modules
        state: absent

    - name: Install app dependencies
      npm:
        path: /home/ubuntu/my-node-app
        state: present
        ci: yes

    - name: Build the Node.js app
      command: npm run build
      args:
        chdir: /home/ubuntu/my-node-app

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Start the Node.js app with PM2
      command: pm2 start /home/ubuntu/my-node-app/dist/index.js --name "my-node-app"
      args:
        chdir: /home/ubuntu/my-node-app
      become: yes
